name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:

- job: Setup
  pool:
    vmImage: windows-latest
  displayName: My Phase
  condition: succeededOrFailed()

