name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:

- job: Setup
  pool:
    vmImage: windows-latest
  displayName: My Phase
  condition: succeededOrFailed()

  steps:
  - checkout: self
    persistCredentials: true

  - task: DownloadBuildArtifacts@0
    condition: succeededOrFailed()
    inputs:
      buildType: specific
      project: f9b79625-2860-4d92-a4ee-57b03fabfd10 # azure-iot-sdks
      pipeline: $(scriptspipelineid) # iot-sdks-internals-scripts pipeline
      buildVersionToDownload: latest
      downloadType: single
      downloadPath: $(System.ArtifactsDirectory)/scripts
      artifactName: c
